import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';// sidebars.js
const sidebars = {
  // 文档类侧边栏
  docsCategorySidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs-category', // 对应 docs/docs-category 目录
    },
  ],
  // 网址类侧边栏
  urlCategorySidebar: [
    {
      type: 'autogenerated',
      dirName: 'url-category', // 对应 docs/url-category 目录
    },
  ],
};

module.exports = sidebars;